server:
  port: 8083
spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://postgres:5432/fooddb
    username: food
    password: foodpw
  jpa:
    hibernate:
      ddl-auto: validate
  cache:
    type: none # we provide a composite CacheManager bean
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
